name: Select Runner and Create File

on:
  workflow_dispatch:
    inputs:
      runner_label:
        description: "Select the runner label"
        required: true
        default: "EC2AMAZ-5BQ8D0F"
        type: choice
        options:
          - EC2AMAZ-5BQ8D0F
          - EC2AMAZ-9UU0BV5

jobs:
  create-file:
    runs-on: [self-hosted, ${{ inputs.runner_label }}]  # Dynamically assign runner
    steps:
      - name: Create file based on runner
        run: |
          if [ "${{ inputs.runner_label }}" == "EC2AMAZ-5BQ8D0F" ]; then
            echo "This file is created on EC2AMAZ-5BQ8D0F" > D:\runnerone.txt
          else
            echo "This file is created on EC2AMAZ-9UU0BV5" > D:\secondrunner.txt
          fi
