name: Create Files on Specific Runners

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Choose the target runner'
        required: true
        default: 'firstrunner'
        type: choice
        options:
          - firstrunner
          - secondrunner

jobs:
  create-first-file:
    if: ${{ github.event.inputs.target == 'firstrunner' }}
    runs-on: [self-hosted, Windows, X64, test]
    steps:
      - name: Create first.txt on firstrunner
        run: echo "This is first.txt" > first.txt

  create-second-file:
    if: ${{ github.event.inputs.target == 'secondrunner' }}
    runs-on: [self-hosted, Windows, X64, dev]
    steps:
      - name: Create second.txt on secondrunner
        run: echo "This is second.txt" > second.txt
