name: Create Files on Specific Runners

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  create-runnerone-file:
    runs-on: [self-hosted, EC2AMAZ-5BQ8D0F]  # Runs on first machine
    steps:
      - name: Create runnerone.txt
        run: echo "This file is created on EC2AMAZ-5BQ8D0F" > D:\runnerone.txt

  create-secondrunner-file:
    runs-on: [self-hosted, EC2AMAZ-9UU0BV5]  # Runs on second machine
    steps:
      - name: Create secondrunner.txt
        run: echo "This file is created on EC2AMAZ-9UU0BV5" > D:\secondrunner.txt
